name : Testing
on :
  workflow_dispatch:
    inputs:
      message:
      description: "Enter a message"
      required: true
jobs:
  testaction:
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name : print the message
    -run : |
      echo "print the message ${{ github.event.input.message }}"
      
      
      
    
