name: test inputs actions
on:
  workflow_dispatch:
    inputs:
      message:
        required: true
        description : "Enter a message"
jobs:
  testaction:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name : print the message
      run : |
        msg = $${{ github.event.input.message }}
        echo "print the message ${msg} "
      
      
      
    
