name: Mixed inputs
on:
  workflow_dispatch:
    inputs:
      message:
        required: true
        description : "Enter a message"
jobs:
  testaction:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name : print the message
    -run : |
      echo "print the message ${{ github.event.input.message }}"
      
      
      
    
